### ISSUE TITLE
ElasticSearch Store has flaky test, may be non-threadsafe

### ISSUE THREAD

**Issue by johnynek** [twitter/storehaus#263]
```
[info] ElasticSearch Store
[info] - should Put a value *** FAILED ***
[info]   org.elasticsearch.indices.IndexMissingException: [test_index] missing
[info]   at org.elasticsearch.cluster.metadata.MetaData.convertFromWildcards(MetaData.java:633)
[info]   at org.elasticsearch.cluster.metadata.MetaData.concreteIndices(MetaData.java:532)
[info]   at org.elasticsearch.action.support.broadcast.TransportBroadcastOperationAction$AsyncBroadcastAction.<init>(TransportBroadcastOperationAction.java:129)
[info]   at org.elasticsearch.action.support.broadcast.TransportBroadcastOperationAction.doExecute(TransportBroadcastOperationAction.java:75)
[info]   at org.elasticsearch.action.support.broadcast.TransportBroadcastOperationAction.doExecute(TransportBroadcastOperationAction.java:46)
[info]   at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:63)
[info]   at org.elasticsearch.client.node.NodeIndicesAdminClient.execute(NodeIndicesAdminClient.java:72)
[info]   at org.elasticsearch.client.support.AbstractIndicesAdminClient.refresh(AbstractIndicesAdminClient.java:395)
[info]   at org.elasticsearch.action.admin.indices.refresh.RefreshRequestBuilder.doExecute(RefreshRequestBuilder.java:49)
[info]   at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85)
[info]   ...
```

**Comment by BenFradet** [comment]
@johnynek I think we can close this :smile:

**Comment by johnynek** [comment]
yessir! Thanks
